[package]

name = "rust-life"
version = "0.0.3"
authors = ["Mike MacDonald <crazymykl@gmail.com>"]

[features]
unstable = []

[dependencies]

threadpool = "0.1"
rand = "0.3"
num_cpus = "0.1"
piston_window = "0.33.0"
image = "0.6.0"
