[package]

name = "rust-life"
version = "0.8.0"
authors = ["Mike MacDonald <crazymykl@gmail.com>"]
description = "An implementation of Conway's Game of Life."
license = "MIT"
repository = "https://github.com/crazymykl/rust-life"
edition = '2024'

[features]

default = ["gui", "rayon"]
unstable = []
gui = ["dep:winit", "dep:wgpu", "dep:futures", "dep:bytemuck"]

[[bench]]

name = "e2e"

[dependencies]

rand = "0.10.2"
winit = { version = "0.30.13", optional = true }
wgpu = { version = "29.0.4", optional = true }
futures = { version = "0.3.31", optional = true }
bytemuck = { version = "1.25.2", optional = true }
rayon = { version = "1.10.0", optional = true }
clap = { version = "4.5.26", features = ["derive"] }

[dev-dependencies]

assert_cmd = "2.0.16"
naga = "29.0.4"
