[package]

name = "rust-life"
version = "0.2.4"
authors = ["Mike MacDonald <crazymykl@gmail.com>"]
description = "An implementation of Conway's Game of Life."
license = "MIT"
repository = "https://github.com/crazymykl/rust-life"

[features]
unstable = []

[dependencies]

rand = "0.3"
piston_window = "0.68.0"
image = "0.14.0"
rayon = "0.8.0"
