[package]

name = "rust-life"
version = "0.0.2"
authors = ["Mike MacDonald <crazymykl@gmail.com>"]

[features]
unstable = []

[dependencies]

threadpool = "0.1"
rand = "0.3"
num_cpus = "0.1"
piston_window = "0.11.0"
