[package]

name = "rust-life"
version = "0.1.3"
authors = ["Mike MacDonald <crazymykl@gmail.com>"]
description = "An implementation of Conway's Game of Life."
license = "MIT"
repository = "https://github.com/crazymykl/rust-life"

[features]
unstable = []

[dependencies]

threadpool = "1.3"
rand = "0.3"
num_cpus = "0.2.11"
piston_window = "0.58.0"
image = "0.10.0"
