name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: test
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    env: 
      NEXTEST_PROFILE: ${{ matrix.os == 'ubuntu-latest' && matrix.toolchain == 'stable' && 'ci' || 'default' }}
      
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - uses: taiki-e/install-action@nextest
      - run: cargo fmt --check
      - run: cargo build --verbose --no-default-features
      - run: cargo clippy -- -D clippy::all
      - run: cargo nextest run --verbose --no-default-features
      - run: cargo clean
      - run: cargo build --verbose --features test_mainthread
      - if: ${{ matrix.os }} == "windows-latest"
        uses: ssciwr/setup-mesa-dist-win@v2
      - uses: coactions/setup-xvfb@v1
        with:
          run: cargo nextest run --verbose --features test_mainthread
      - name: Upload test results to Codecov
        if: ${{ env.NEXTEST_PROFILE == 'ci' && !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/junit.xml

  bench:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps: 
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo build --release --verbose
      - if: ${{ matrix.os }} == "windows-latest"
        uses: ssciwr/setup-mesa-dist-win@v2
      - uses: coactions/setup-xvfb@v1
        with: 
          run: cargo bench --verbose --features unstable

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - uses: coactions/setup-xvfb@v1
        with:
          run: cargo llvm-cov nextest --ignore-filename-regex src/args.rs --codecov --no-cfg-coverage --features test_mainthread --output-path codecov.json
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true
      